# Generated by Django 5.1.1 on 2024-10-15 04:51

import VitaDating.helpers
import activity.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(default=VitaDating.helpers.gen_uuid, unique=True)),
                ('activity', models.FileField(upload_to=VitaDating.helpers.user_vid_path)),
                ('privacy', models.CharField(choices=[('F', 'Friends'), ('PRV', 'Private'), ('PUB', 'Public')], max_length=3)),
                ('likes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=60, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('replies', models.JSONField(default=activity.models.default_replies)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=VitaDating.helpers.user_sound_path)),
            ],
        ),
    ]
