# Generated by Django 5.1.1 on 2024-10-15 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='like_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='comments',
            field=models.ManyToManyField(blank=True, to='activity.comment'),
        ),
        migrations.AddField(
            model_name='sound',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sound',
            name='original_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='og_sound', to='activity.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_sound', to='activity.sound'),
        ),
    ]
