# Generated by Django 3.2 on 2021-04-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailauth',
            name='token',
            field=models.IntegerField(),
        ),
    ]
