# Generated by Django 3.2 on 2021-04-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('vibe_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viber',
            name='videos',
            field=models.ManyToManyField(related_name='viber_videos', to='video.Video'),
        ),
    ]
