# Generated by Django 3.2 on 2021-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vibe_user', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viber',
            name='liked_videos',
            field=models.ManyToManyField(related_name='liked_videos_list', to='video.Video'),
        ),
        migrations.AddField(
            model_name='viber',
            name='sounds',
            field=models.ManyToManyField(related_name='viber_sounds', to='video.Sound'),
        ),
        migrations.AddField(
            model_name='viber',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='viber',
            name='videos',
            field=models.ManyToManyField(related_name='viber_videos', to='video.Video'),
        ),
    ]
