# Generated by Django 3.2 on 2021-04-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_user', '0002_viber_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='viber',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
