# Generated by Django 5.1.1 on 2024-10-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_user', '0003_auto_20210419_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='viber',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
