# Generated by Django 3.1.7 on 2021-04-06 00:55

from django.db import migrations, models
import django.utils.timezone
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('replies', models.JSONField(default=video.models.default_replies)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=video.models.user_dir_path)),
                ('privacy', models.CharField(choices=[('F', 'Friends'), ('PRV', 'Private'), ('PUB', 'Public')], max_length=3)),
                ('likes', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=70)),
                ('comments', models.ManyToManyField(to='video.Comment')),
            ],
        ),
    ]
