# Generated by Django 3.2 on 2021-04-09 07:02

from django.db import migrations, models
import vibetube.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='audio_file',
            field=models.FileField(upload_to=vibetube.helpers.user_sound_path),
        ),
    ]
