# Generated by Django 3.1.7 on 2021-04-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, to='video.Comment'),
        ),
    ]
