# Generated by Django 3.1.7 on 2021-04-06 01:56

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210406_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.IntegerField(default=video.models.gen_uuid, unique=True),
        ),
    ]
