<<<<<<< HEAD
# Generated by Django 3.2 on 2021-04-13 03:04
=======
# Generated by Django 3.2 on 2021-04-12 22:41
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210412_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='reciever',
            new_name='to',
        ),
    ]
